"""ROSClaw Code Generator — controlled framework generation from wiki knowledge.

Generates code skeletons with source citations.
Strict limits:
  - NEVER generates full control loops
  - ALWAYS includes AUTO-GENERATED warning header
  - ALWAYS cites physical parameter sources
  - REFUSES to generate if unresolved conflicts exist for parameters
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

import wiki_engine as engine

logger = logging.getLogger("rosclaw.code_generator")

_AUTO_GENERATED_HEADER = """# ⚠️ AUTO-GENERATED CODE — SAFETY BOUNDARIES VERIFIED
# Generated by ROSClaw Wiki Phase 12
# This is a SKELETON only. Do NOT use in production without review.
# All physical parameters are cited from the wiki; verify against primary sources.

"""

# Regex to find parameter declarations in a single line
# Matches: step_height = 0.05 m  or  - step_height = 0.05 m
_PARAM_DECL_RE = re.compile(
    r"(?i)^\s*[-*]?\s*([\w_]+)\s*[:=]\s*([0-9.]+)\s*([a-zA-Z°/%·/]+)?\s*$"
)

# Regex to find citations like [[Page Title]]
_CITATION_RE = re.compile(r"\[\[([^\]|]+)(?:\|[^\]]+)?\]\]")


def _extract_parameters_from_body(body: str) -> list[dict[str, Any]]:
    """Scan page body for parameter declarations.

    Returns list of dicts: {name, value, unit, line}.
    """
    params: list[dict[str, Any]] = []
    for line in body.splitlines():
        match = _PARAM_DECL_RE.match(line)
        if not match:
            continue
        name, value_str, unit = match.groups()
        try:
            if "." in value_str:
                val = float(value_str)
            else:
                val = int(value_str)
        except ValueError:
            val = value_str
        params.append({
            "name": name.strip(),
            "value": val,
            "unit": (unit or "").strip(),
            "line": line.strip(),
        })
    return params


def _extract_citations_from_body(body: str) -> list[str]:
    """Find all [[Page Title]] citations in body."""
    return [f"[[{m.group(1).strip()}]]" for m in _CITATION_RE.finditer(body)]


def _has_unresolved_conflicts(body: str) -> list[str]:
    """Return list of parameter names with unresolved conflicts."""
    unresolved: list[str] = []
    in_resolved = False
    for line in body.splitlines():
        if line.strip().startswith("### 已裁决冲突"):
            in_resolved = True
            continue
        if in_resolved and line.startswith("#") and not line.startswith("###"):
            break
        if in_resolved and "status: `unresolved`" in line:
            # Extract parameter name from preceding line
            m = re.search(r"\*\*(\w+)\*\*", line)
            if m:
                unresolved.append(m.group(1))
    return unresolved


def _check_safety_boundary(param_name: str, value: float, hardware_limit: float | None) -> tuple[str, bool]:
    """Check parameter against hardware safety limits.

    Phase 14 GREEN/AMBER/RED safety label system:
      GREEN  — ratio < 0.80  (safe, auto-merge eligible)
      AMBER  — ratio >= 0.80 but < 1.0  (needs human review)
      RED    — ratio >= 1.0  (exceeds limit, blocked)

    Returns:
        (severity, is_safe) where severity is one of "green", "amber", "red".
    """
    if hardware_limit is None or hardware_limit <= 0:
        return "green", True
    try:
        ratio = float(value) / float(hardware_limit)
    except (ValueError, TypeError):
        return "green", True
    if ratio >= 1.0:
        return "red", False
    if ratio >= 0.80:
        return "amber", True
    return "green", True


def _check_physical_constraints_cognitive(
    param_name: str,
    value: float,
    constraint_graph: Any | None = None,
) -> dict[str, Any]:
    """Cognitive physics firewall using constraint graph (Phase 16).

    When a ConstraintGraph is available, performs deep causal reasoning:
      - Hardware limits via CONSTRAINED_BY edges
      - Degradation paths (high current → temperature → motor life)
      - Latency constraints (inference time vs control period)
      - Context-aware adjustments (simulation vs real_world)

    Falls back to basic safety boundary check when no graph is available.

    Returns:
        Dict with safety_level (OK | WARNING | CRITICAL), action
        (ALLOW | REVIEW_REQUIRED | REFUSE), violations, causal_chain,
        recommendation.
    """
    if constraint_graph is not None:
        try:
            return constraint_graph.check_physical_constraints(param_name, value)
        except Exception as exc:
            logger.debug("Cognitive firewall error for %s: %s", param_name, exc)

    # Fallback to basic Phase 14 safety boundary
    severity, is_safe = _check_safety_boundary(param_name, value, None)
    if severity == "red":
        return {
            "safety_level": "CRITICAL",
            "action": "REFUSE",
            "violations": [{
                "severity": "critical",
                "property": param_name,
                "reason": "Exceeds hardware safety boundary",
            }],
            "causal_chain": [],
            "recommendation": "Parameter exceeds safety limit.",
        }
    if severity == "amber":
        return {
            "safety_level": "WARNING",
            "action": "REVIEW_REQUIRED",
            "violations": [{
                "severity": "warning",
                "property": param_name,
                "reason": "Parameter >= 80% of hardware limit",
            }],
            "causal_chain": [],
            "recommendation": "Parameter near safety boundary; review required.",
        }
    return {
        "safety_level": "OK",
        "action": "ALLOW",
        "violations": [],
        "causal_chain": [],
        "recommendation": "No physical constraints violated.",
    }


def _find_local_code_entity(entity_name: str, wiki_root: str) -> Path | None:
    """Check if a local code repository entity page exists for this entity.

    Returns the page path if found, None otherwise.
    """
    root = Path(wiki_root)
    slug = engine.generate_page_id(entity_name)

    # Search in entities/ for code repository pages that mention this entity
    for md_file in (root / "entities").rglob("*.md"):
        try:
            meta, body = engine.parse_frontmatter(md_file.read_text(encoding="utf-8"))
            # Match by title, slug, or body mention
            if meta.get("title") == entity_name:
                return md_file
            if md_file.stem == slug:
                return md_file
            # Check if body mentions the entity in relationships
            if f"[[{entity_name}]]" in body:
                return md_file
        except Exception:
            continue
    return None


def _find_page_for_entity(entity_name: str, wiki_root: str) -> Path | None:
    """Find the page file for an entity/algorithm by title or slug."""
    root = Path(wiki_root)
    slug = engine.generate_page_id(entity_name)
    for md_file in root.rglob("*.md"):
        if md_file.stem == slug:
            return md_file
        try:
            meta, _ = engine.parse_frontmatter(md_file.read_text(encoding="utf-8"))
            if meta.get("title") == entity_name:
                return md_file
        except Exception:
            continue
    return None


def generate_code_framework(
    entity_name: str,
    wiki_root: str,
    language: str = "python",
) -> dict[str, Any]:
    """Generate a code framework for an entity/algorithm with source citations.

    Args:
        entity_name: Name of the entity or algorithm.
        wiki_root: Wiki root directory.
        language: Target language (only "python" supported for now).

    Returns:
        Dict with code, citations, warnings, unresolved_conflicts.
    """
    page_path = _find_page_for_entity(entity_name, wiki_root)
    if not page_path:
        return {
            "status": "not_found",
            "entity": entity_name,
            "code": "",
            "citations": [],
            "warnings": [f"No wiki page found for '{entity_name}'"],
            "unresolved_conflicts": [],
        }

    try:
        content = page_path.read_text(encoding="utf-8")
        meta, body = engine.parse_frontmatter(content)
    except Exception as exc:
        return {
            "status": "error",
            "entity": entity_name,
            "code": "",
            "citations": [],
            "warnings": [f"Failed to read page: {exc}"],
            "unresolved_conflicts": [],
        }

    title = meta.get("title", page_path.stem)
    page_type = meta.get("type", "unknown")
    citations = _extract_citations_from_body(body)

    # Check for unresolved conflicts
    unresolved = _has_unresolved_conflicts(body)
    if unresolved:
        return {
            "status": "blocked",
            "entity": entity_name,
            "code": "",
            "citations": citations,
            "warnings": [
                f"Code generation BLOCKED: unresolved conflicts exist for parameters: {', '.join(unresolved)}"
            ],
            "unresolved_conflicts": unresolved,
        }

    # Extract parameters from wiki body and merge with judgment data
    params = _extract_parameters_from_body(body)

    # Load judgments and merge into params
    _hardware_limits: dict[str, float | None] = {}
    judgment_lookup: dict[str, dict[str, Any]] = {}
    try:
        from judgment_generator import get_judgment
        j_result = get_judgment(title, wiki_root=wiki_root)
        if j_result.get("status") == "found":
            for j in j_result.get("judgments", []):
                if not j.get("unresolved"):
                    param_name = j["parameter"]
                    judgment_lookup[param_name.upper()] = {
                        "value": j["recommended_value"],
                        "unit": j.get("unit", ""),
                        "source": f"judgment ({j['confidence']})",
                        "hardware_limit": j.get("hardware_limit"),
                        "confidence": j.get("confidence", 0.0),
                        "sources": j.get("sources", []),
                    }
                    _hardware_limits[param_name.upper()] = j.get("hardware_limit")
    except Exception:
        pass

    # Merge judgment data into body params (judgment values take precedence)
    merged_params: list[dict[str, Any]] = []
    seen_body: set[str] = set()
    for p in params:
        name = p["name"].upper()
        seen_body.add(name)
        j = judgment_lookup.get(name)
        if j:
            merged_params.append({
                "name": p["name"],
                "value": j["value"],
                "unit": j.get("unit") or p.get("unit", ""),
                "source": j.get("source", ""),
                "hardware_limit": j.get("hardware_limit"),
                "confidence": j.get("confidence", 0.0),
                "sources": j.get("sources", []),
            })
        else:
            merged_params.append(p)

    # Add judgment-only params
    for name, j in judgment_lookup.items():
        if name not in seen_body:
            merged_params.append({
                "name": j.get("sources", [""])[0].strip("[]") if j.get("sources") else name,
                "value": j["value"],
                "unit": j.get("unit", ""),
                "source": j.get("source", ""),
                "hardware_limit": j.get("hardware_limit"),
                "confidence": j.get("confidence", 0.0),
                "sources": j.get("sources", []),
            })

    params = merged_params

    # Check for local code entity
    code_entity_path = _find_local_code_entity(entity_name, wiki_root)
    code_entity_title = None
    if code_entity_path:
        try:
            cem, _ = engine.parse_frontmatter(code_entity_path.read_text(encoding="utf-8"))
            code_entity_title = cem.get("title", code_entity_path.stem)
        except Exception:
            pass

    # Phase 10: query code knowledge graph
    graph_refs: list[dict[str, Any]] = []
    try:
        import code_knowledge_graph as ckg
        node = ckg.find_function_implementation(entity_name)
        if node:
            graph_refs.append({
                "name": node["name"],
                "file": node.get("file", ""),
                "repo": node.get("repo", ""),
                "type": node.get("type", ""),
                "docstring": node.get("docstring", "")[:100],
            })
        # Also search for classes matching the entity
        graph = ckg.load_code_graph()
        for n in graph.get("nodes", []):
            if n["type"] == "class" and entity_name.lower() in n["name"].lower():
                graph_refs.append({
                    "name": n["name"],
                    "file": n.get("file", ""),
                    "repo": n.get("repo", ""),
                    "type": "class",
                    "docstring": n.get("docstring", "")[:100],
                })
    except Exception:
        pass

    # Build code skeleton
    lines: list[str] = [_AUTO_GENERATED_HEADER]
    lines.append(f"# Entity: {title}\n")
    lines.append(f"# Type: {page_type}\n")
    lines.append(f"# Source page: {page_path.name}\n")
    if code_entity_title:
        lines.append(f"# See also: [[{code_entity_title}]] for reference implementation\n")
    if graph_refs:
        lines.append("# Existing code references found in knowledge graph:\n")
        for ref in graph_refs:
            lines.append(f"#   - {ref['type']} {ref['name']} in {ref['repo']}/{ref['file']}\n")
    lines.append("\n")

    if language == "python":
        class_name = "".join(
            w.capitalize()
            for part in title.replace("-", " ").replace("_", " ").split(" ")
            for w in [part]
            if w
        )
        if not class_name:
            class_name = "GeneratedClass"

        # Phase 10: add imports for referenced code
        if graph_refs:
            lines.append("# --- Auto-generated imports from code graph ---\n")
            for ref in graph_refs[:3]:
                mod_path = ref["file"].replace(".py", "").replace("/", ".")
                lines.append(f"# from {mod_path} import {ref['name']}  # existing implementation\n")
            lines.append("\n")

        lines.append(f"class {class_name}Controller:\n")
        lines.append('    """Auto-generated controller skeleton."""\n\n')

        warnings: list[str] = []

        # Constants from parameters
        if params:
            lines.append("    # --- Physical Parameters (verify before use) ---\n")
            seen_names: set[str] = set()
            for p in params:
                name = p["name"].upper()
                if name in seen_names:
                    continue
                seen_names.add(name)

                # Safety boundary check
                val = p["value"]
                try:
                    numeric_val = float(val) if isinstance(val, (int, float)) else float(str(val))
                except (ValueError, TypeError):
                    numeric_val = 0.0
                hw_limit = p.get("hardware_limit") or _hardware_limits.get(name)
                severity, is_safe = _check_safety_boundary(name, numeric_val, hw_limit)

                if severity == "red":
                    lines.append(f"    # [!CRITICAL] {name} = {val!r} exceeds hardware limit ({hw_limit}). Parameter REJECTED.\n")
                    lines.append(f"    # {name} = {val!r}  # REFUSED — out of spec\n")
                    warnings.append(f"[!CRITICAL] {name}: {val} exceeds hardware limit {hw_limit}. Code generation blocked for this parameter.")
                    continue

                if severity == "amber":
                    lines.append(f"    # [!WARNING] {name} = {val!r} is >=80% of hardware limit ({hw_limit}). Review required.\n")
                    warnings.append(f"[!WARNING] {name}: {val} is >=80% of hardware limit {hw_limit}.")

                # Try to emit numeric literal if possible
                display_val = val
                try:
                    if isinstance(val, str):
                        if "." in val:
                            display_val = float(val)
                        else:
                            display_val = int(val)
                except (ValueError, TypeError):
                    pass

                unit_comment = f"  # unit: {p['unit']}" if p.get("unit") else ""
                source_comment = f"  # source: {p.get('source', 'wiki page')}" if "source" in p else ""
                ref_comment = ""
                if p.get("sources"):
                    ref_comment = f"  # Ref: {p['sources'][0]} (confidence: {p.get('confidence', 'N/A')})"
                lines.append(f"    {name} = {display_val!r}{unit_comment}{source_comment}{ref_comment}\n")
            lines.append("\n")

        lines.append("    def __init__(self):\n")
        lines.append("        pass\n\n")

        lines.append("    def setup(self):\n")
        lines.append('        """Initialize hardware connections."""\n')
        lines.append("        # TODO: implement setup\n")
        lines.append("        pass\n\n")

        lines.append("    def compute(self, observation):\n")
        lines.append('        """Compute next action from observation.\n\n')
        lines.append("        Args:\n")
        lines.append("            observation: Current sensor reading.\n\n")
        lines.append("        Returns:\n")
        lines.append("            action: Control command.\n")
        lines.append('        """\n')
        lines.append("        # TODO: implement control logic\n")
        lines.append("        raise NotImplementedError('Control loop must be implemented by human engineer.')\n\n")

        lines.append("    def shutdown(self):\n")
        lines.append('        """Safe shutdown sequence."""\n')
        lines.append("        # TODO: implement safe shutdown\n")
        lines.append("        pass\n")
    else:
        lines.append(f"# Language '{language}' not yet supported.\n")

    code = "".join(lines)

    if not params:
        warnings.append("No physical parameters were found on the wiki page. Generated code has no constants.")
    warnings.append("This is a SKELETON. Do not deploy without human review.")

    return {
        "status": "generated",
        "entity": entity_name,
        "code": code,
        "citations": citations,
        "warnings": warnings,
        "unresolved_conflicts": unresolved,
    }


def sync_check(
    entity_name: str,
    wiki_root: str,
    code_paths: list[str] | None = None,
    auto_pr: bool = False,
) -> dict[str, Any]:
    """Scan code files for parameters referencing a wiki entity and compare with judgments.

    Generates a sync warning report but does NOT modify any code.
    Report is written to wiki/log.md.

    Args:
        entity_name: Wiki entity to check (e.g., "Unitree-G1").
        wiki_root: Wiki root directory.
        code_paths: Optional list of file paths to scan. If None, scans data/raw/code/.
        auto_pr: If True, also generate a PR proposal for discrepancies.

    Returns:
        Dict with report markdown, warnings list, total_checked, and optionally pr_data.
    """
    from pathlib import Path
    import ast

    root = Path(wiki_root)

    # Load judgments for this entity
    try:
        from judgment_generator import get_judgment
        j_result = get_judgment(entity_name, wiki_root=wiki_root)
        judgments = j_result.get("judgments", []) if j_result.get("status") == "found" else []
    except Exception as exc:
        return {
            "status": "error",
            "entity": entity_name,
            "report": f"Failed to load judgments: {exc}",
            "warnings": [],
            "total_checked": 0,
        }

    if not judgments:
        return {
            "status": "no_judgments",
            "entity": entity_name,
            "report": f"No judgments found for '{entity_name}'. Nothing to check.",
            "warnings": [],
            "total_checked": 0,
            "discrepancies": 0,
            "findings": [],
        }

    # Build judgment lookup by parameter name
    judgment_by_param: dict[str, dict[str, Any]] = {}
    for j in judgments:
        param = j["parameter"].upper()
        judgment_by_param[param] = j

    # Determine code paths to scan
    if code_paths is None:
        scan_root = Path("data/raw/code")
        if scan_root.exists():
            code_paths = [str(p) for p in scan_root.rglob("*.py")]
        else:
            code_paths = []

    findings: list[dict[str, Any]] = []

    for code_path in code_paths:
        path = Path(code_path)
        if not path.exists():
            continue
        try:
            source = path.read_text(encoding="utf-8")
            tree = ast.parse(source)
        except SyntaxError:
            continue
        except Exception:
            continue

        for node in ast.walk(tree):
            if isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name):
                        param_name = target.id.upper()
                        if param_name in judgment_by_param:
                            # Extract value
                            code_value = None
                            if isinstance(node.value, ast.Constant):
                                code_value = node.value.value
                            elif isinstance(node.value, ast.Num):  # Python <3.8 compat
                                code_value = node.value.n

                            j = judgment_by_param[param_name]
                            try:
                                j_val = float(j["recommended_value"])
                                c_val = float(code_value) if code_value is not None else None
                            except (ValueError, TypeError):
                                continue

                            if c_val is not None and c_val != j_val:
                                hw_limit = j.get("hardware_limit")
                                deviation = ((c_val - j_val) / j_val * 100) if j_val != 0 else 0
                                findings.append({
                                    "file": str(path),
                                    "line": node.lineno,
                                    "parameter": param_name,
                                    "code_value": c_val,
                                    "judgment_value": j_val,
                                    "unit": j.get("unit", ""),
                                    "confidence": j.get("confidence", 0.0),
                                    "deviation_percent": round(deviation, 2),
                                    "hardware_limit": hw_limit,
                                })

    # Build markdown report
    report_lines: list[str] = [
        f"## Sync Check Report: {entity_name}",
        f"**Generated**: {__import__('datetime').datetime.now().isoformat()}",
        f"**Judgment Source**: {judgments[0].get('sources', ['N/A'])[0]} (confidence: {judgments[0].get('confidence', 'N/A')})",
        "",
    ]

    warnings: list[str] = []

    if findings:
        report_lines.append("### ⚠️ Outdated Code Found")
        report_lines.append("")
        for f in findings:
            report_lines.append(f"- **File**: `{f['file']}`")
            report_lines.append(f"  - **Line**: {f['line']}")
            report_lines.append(f"  - **Parameter**: `{f['parameter']}`")
            report_lines.append(f"  - **Code Value**: `{f['code_value']}` {f['unit']}")
            report_lines.append(f"  - **Wiki Judgment**: `{f['judgment_value']}` {f['unit']} (confidence: {f['confidence']})")
            report_lines.append(f"  - **Deviation**: {f['deviation_percent']:+.1f}%")
            action = f"Update to {f['judgment_value']} {f['unit']}"
            if f.get("hardware_limit"):
                action += f" with safety boundary check (hardware limit: {f['hardware_limit']} {f['unit']})"
            report_lines.append(f"  - **Action Required**: {action}")
            report_lines.append("")
            warnings.append(
                f"[{f['file']}:{f['line']}] {f['parameter']}: code={f['code_value']} vs judgment={f['judgment_value']} "
                f"({f['deviation_percent']:+.1f}% deviation)"
            )
    else:
        report_lines.append("### ✅ No discrepancies found")
        report_lines.append("")
        report_lines.append(f"Scanned {len(code_paths)} file(s). All checked parameters match wiki judgments.")
        report_lines.append("")

    report_md = "\n".join(report_lines)

    # Append to wiki log
    try:
        engine.append_log(wiki_root, f"sync_check | {entity_name} | {len(findings)} discrepancies | {len(code_paths)} files scanned")
    except Exception:
        pass

    result: dict[str, Any] = {
        "status": "done",
        "entity": entity_name,
        "report": report_md,
        "warnings": warnings,
        "total_checked": len(code_paths),
        "discrepancies": len(findings),
        "findings": findings,
    }

    # Phase 13: Auto PR generation
    if auto_pr and findings:
        try:
            from pr_generator import generate_pr, submit_pr
            pr_result = generate_pr(entity_name, wiki_root, code_paths)
            result["pr_status"] = pr_result.get("status")
            result["pr_reason"] = pr_result.get("reason")
            if pr_result.get("pr"):
                result["pr_data"] = pr_result["pr"]
                # Simulate submission (writes to data/prs/)
                sub = submit_pr({"entity": entity_name, "pr": pr_result["pr"]})
                result["pr_submitted"] = sub.get("status") == "submitted"
                result["pr_file"] = sub.get("file")
            if pr_result.get("status") == "red":
                result["status"] = "red"
                result["report"] = pr_result["report"]
                result["warnings"].append(f"[!CRITICAL] PR refused for {entity_name}: parameters exceed hardware limits.")
        except Exception as exc:
            logger.warning("Auto-PR generation failed: %s", exc)
            result["pr_status"] = "error"
            result["pr_reason"] = str(exc)

    return result


# ── MCP-facing tool ──


def code_generate(entity_name: str, wiki_root: str | None = None, language: str = "python") -> dict[str, Any]:
    """MCP tool: generate a code framework for an entity/algorithm.

    Returns:
        Dict with code, citations, warnings, and unresolved_conflicts.
    """
    if wiki_root is None:
        return {"status": "error", "message": "wiki_root is required"}

    result = generate_code_framework(entity_name, wiki_root, language)

    # Log to wiki log
    if result["status"] in ("generated", "blocked"):
        engine.append_log(
            wiki_root,
            f"code_generator | {result['status']} | [[{entity_name}]]"
        )

    return result
